name: Generate ASCIIDOC document

on:
  push:
    paths-ignore:
      - 'build/**'

jobs:
  asciidoctor_job:
    runs-on: ubuntu-latest
    name: Build Asciidoctor
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build AsciiDoc step
        id: documents
        uses: Analog-inc/asciidoctor-action@v1
        with:
          shellcommand: "asciidoctor -b html5 -o build/doc1/doc1.html doc/doc1/index.adoc"

      - name: Save AsciiDoc step
        uses: actions/upload-artifact@v4
        with:
          name: Output-document
          path: build/doc1/doc1.html
